---

- hosts: all
  become: true
  tasks:
 
  - name: Install updates (CentOS)
  dnf:
    update_only: yes
    update_cache: yes
  when: ansible_distribution == "CentOS"  
  
  - name: Install apache and PHP for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
     when: ansible_distribution == "Ubuntu"

  - name: Install apache and PHP for Centos
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
     when: ansible_distribution == "CentOS"

